
---
jupyter: python3
---

## Executive Summary {-}

```{python}
#| echo: false
#| output: false
import importlib
import content.python.api_calls_v2 as api_calls_v2

importlib.reload(api_calls_v2)

count_assessment_type = api_calls_v2.count_assessment_type
count_completed_assessments = api_calls_v2.count_completed_assessments
get_metric_value = api_calls_v2.get_metric_value
get_structure_count_value = api_calls_v2.get_structure_count_value

spawning_connected_km = get_metric_value("BOWR", "accessible_spawning_all")
spawning_disconnected_km = get_metric_value("BOWR", "disconnected_spawning_all")
spawning_total_km = get_metric_value("BOWR", "total_spawning_all")
spawning_connected_pct = round((spawning_connected_km / spawning_total_km) * 100, 1)

rearing_connected_km = get_metric_value("BOWR", "accessible_rearing_all")
rearing_disconnected_km = get_metric_value("BOWR", "disconnected_rearing_all")
rearing_total_km = get_metric_value("BOWR", "total_rearing_all")
rearing_connected_pct = round((rearing_connected_km / rearing_total_km) * 100, 1)

potentially_disconnect_spawning_structures = get_structure_count_value(
    "bowr_ques_carr", "all_spawning", "structures_that_potentially_disconnect_habitat"
)
potentially_disconnect_rearing_structures = get_structure_count_value(
    "bowr_ques_carr", "all_rearing", "structures_that_potentially_disconnect_habitat"
)
priority_barriers = get_structure_count_value(
    "bowr_ques_carr", "all_spawningrearing", "priority_barriers"
)
non_actionable_spawning = get_structure_count_value(
    "bowr_ques_carr", "all_spawning", "non_actionable_barriers"
)
non_actionable_rearing = get_structure_count_value(
    "bowr_ques_carr", "all_rearing", "non_actionable_barriers"
)
further_field_assessment_spawning = get_structure_count_value(
    "bowr_ques_carr", "all_spawning", "require_further_assessment"
)
further_field_assessment_rearing = get_structure_count_value(
    "bowr_ques_carr", "all_rearing", "require_further_assessment"
)

assessed_structures = count_completed_assessments()
habitat_confirmations = count_assessment_type("Habitat confirmation")
```

The purpose of the Lhtako Dene Nation (LDN) Territory Watershed Connectivity Restoration Plan (WCRP) is to improve understanding of habitat connectivity for Coho Salmon (Oncorhynchus kisutch), Chum Salmon (O. keta), and Sockeye Salmon (O. nerka) in the portions of the Quesnel, Cariboo, Cottonwood, and Bowron watersheds within LDN territory. For practicality, these watersheds will be referred to as “LDN watersheds” throughout the report. Local data and knowledge are combined with connectivity modelling to estimate current connectivity status and identify structures that potentially block the most habitat. This informs the prioritization of field assessments to close the most significant knowledge gaps efficiently. Information from field assessments of barrier status and habitat condition are incorporated into the model, improving understanding of which barriers block the most habitat, and informing restoration prioritization. As knowledge gaps are closed and barriers are addressed, this plan will be revised to summarize progress and provide updated estimates of connectivity status and the status and relative importance of remaining structures. 

In the LDN watersheds, `{python} spawning_connected_km` km of Pacific salmon spawning habitat are currently connected to the ocean and `{python} spawning_disconnected_km` km are disconnected from it. This means that `{python} spawning_connected_pct`% of the `{python} spawning_total_km` km of total habitat is connected. 

In the LDN watersheds, `{python} rearing_connected_km` km of Pacific salmon rearing habitat are currently connected to the ocean and `{python} rearing_disconnected_km` km are disconnected from it. This means that `{python} rearing_connected_pct`% of the `{python} rearing_total_km` km of total habitat is connected. 

In the LDN watersheds, `{python} potentially_disconnect_spawning_structures` structures potentially disconnect Pacific salmon spawning habitat. Of these, `{python} priority_barriers` are identified as barriers in need of rehabilitation (priority barriers), `{python} non_actionable_spawning` are identified as barriers that do not warrant rehabilitation (non-actionable), and `{python} further_field_assessment_spawning` require further field assessment. 

In the LDN watersheds, `{python} potentially_disconnect_rearing_structures` structures potentially disconnect Pacific salmon rearing habitat. Of these, `{python} priority_barriers` are identified as barriers in need of rehabilitation (priority barriers), `{python} non_actionable_rearing` are identified as barriers that do not warrant rehabilitation (non-actionable), and `{python} further_field_assessment_rearing` require further field assessment.

![Figure 1: Map of Pacific salmon spawning habitat and structures that are confirmed or potential barriers to fish passage in the LDN watersheds as of May 2026. Structure data were obtained from BCFishPass and the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that one or more Pacific salmon species could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by one or more Pacific salmon species for spawning. Available local knowledge and data were incorporated and overruled habitat model results. Thick red lines represent habitat considered to be fully disconnected (upstream of barriers or unassessed structures). Excluded structures (e.g., those found to be passable) are not shown on this map.](content/images/LDN_spawning_2026-05-22.png){fig-cap-location="top"}

![Figure 2: Map of Pacific salmon rearing habitat and structures that are confirmed or potential barriers to fish passage in the LDN watersheds as of May 2026. Structure data were obtained from BCFishPass and the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that one or more Pacific salmon species could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by one or more Pacific salmon species for rearing. Available local knowledge and data were incorporated and overruled habitat model results. Thick red lines represent habitat considered to be fully disconnected (upstream of barriers or unassessed structures). Excluded structures (e.g., those found to be passable) are not shown on this map.](content/images/LDN_rearing_2026-05-22.png){fig-cap-location="top"}

![Figure 3: Habitat Accumulation Curve (HAC) showing structures in the LDN watersheds that block Pacific salmon spawning habitat, as of May 2026. Structures are ranked based on how much (km) spawning habitat for Pacific salmon is upstream. The y-axis represents the cumulative amount of potential habitat gain (km). Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown.](content/images/LDN_HAC_spawning.png){fig-cap-location="top"}

![Figure 4: Habitat Accumulation Curve (HAC) showing structures in the LDN watersheds that block Pacific salmon rearing habitat, as of May 2026. Structures are ranked based on how much (km) rearing habitat for Pacific salmon is upstream. The y-axis represents the cumulative amount of potential habitat gain (km). Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown.](content/images/LDN_HAC_rearing.png){fig-cap-location="top"}

This WCRP was initiated in 2023. The initial development of the WCRP included portions of the Quesnel, Bowron, and Cariboo watersheds. Several scoping exercises were completed by the planning team to help guide the initial development of the WCRP, including a threats assessment that detailed the extent, severity, and overall threat of all five barrier types in the Bowron, Quesnel, and Cariboo (see Appendix D). Situation analyses were also completed by the planning team to identify factors that contribute to the prevalence of culverts and dams on the landscape (see Appendix E). In 2025, the geographic scope of the WCRP expanded to include portions of the Cottonwood watershed. Since 2023, the passability of `{python} assessed_structures` structures has been assessed, and further habitat assessments were completed at `{python} habitat_confirmations` of these.  
