---
jupyter: python3
---

# Progress Reporting {-}

## Progress Reporting {-}

```{python}
#| echo: false
#| output: false
import sys
import importlib
from pathlib import Path

sys.path.append(str(Path.cwd().resolve().parent))

import content.python.api_calls_v2 as api_calls_v2

importlib.reload(api_calls_v2)

count_assessment_type = api_calls_v2.count_assessment_type
count_completed_assessments = api_calls_v2.count_completed_assessments

assessed_structures = count_completed_assessments()
habitat_confirmations = count_assessment_type("Habitat confirmation")
```

This WCRP was initiated in 2023. The initial development of the WCRP included portions of the Quesnel, Bowron, and Cariboo watersheds. Several scoping exercises were completed by the planning team to help guide the initial development of the WCRP, including a threats assessment that detailed the extent, severity, and overall threat of all five barrier types in the Bowron, Quesnel, and Cariboo (see Appendix D). Situation analyses were also completed by the planning team to identify factors that contribute to the prevalence of culverts and dams on the landscape (see Appendix E). In 2025, the geographic scope of the WCRP expanded to include portions of the Cottonwood watershed. Since 2023, the passability of `{python} assessed_structures` structures has been assessed, and further habitat assessments were completed at `{python} habitat_confirmations` of these.  

## Rehabilitated Barriers {-}

No barriers were rehabilitated through the implementation of this WCRP as of May 2026. 

## Annual Progress Report {-}


## Priority Barriers {-}

```{r tbl6, echo = FALSE, results = 'asis'}
#| label: tbl6
#| tbl-cap: 'Table 6: Structures in the LDN watersheds that are confirmed as barriers to fish passage for Pacific salmon with confirmed spawning or rearing habitat upstream, as of May 2026. Habitat gain represents the amount (km) of spawning or rearing habitat upstream of that barrier to the next structure that will be reconnected for Pacific salmon if that barrier is addressed. The number of structures in a set represents the number of structures that must be addressed concurrently to maximize habitat connectivity. Barriers known to be partially passable are indicated by “yes”, with further details provided in the adjacent column.'
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/LDN_priority_barriers.csv", check.names=FALSE)
ft <- flextable(data)

ft <- format_flextable(ft)
ft
```